class ZCL_CRM_BASE_ORDER_ITEM definition
  public
  abstract
  create protected .

public section.

  interfaces ZIF_CRM_ENTITY .
  interfaces ZIF_CRM_ORDER_ITEM .
protected section.
private section.
ENDCLASS.



CLASS ZCL_CRM_BASE_ORDER_ITEM IMPLEMENTATION.
  METHOD ZIF_CRM_ORDER_ITEM~ADD_EXTENSION_STRUCTURE.

  ENDMETHOD.

  METHOD ZIF_CRM_ORDER_ITEM~ADD_PRODUCT_I.

  ENDMETHOD.

  METHOD ZIF_CRM_ORDER_ITEM~ADD_REFERENCE_OBJECT.

  ENDMETHOD.

  METHOD ZIF_CRM_ENTITY~CREATE.

  ENDMETHOD.

  METHOD ZIF_CRM_ENTITY~DELETE.

  ENDMETHOD.

  METHOD ZIF_CRM_ENTITY~GET_ATTRIBUTES.

  ENDMETHOD.

  METHOD ZIF_CRM_ENTITY~GET_ATTRIBUTE_TYPE_NAME.

  ENDMETHOD.

  METHOD ZIF_CRM_ENTITY~GET_ENTITY_ID.

  ENDMETHOD.

  METHOD ZIF_CRM_ENTITY~GET_TRANSACTION_CONTEXT.

  ENDMETHOD.

  METHOD ZIF_CRM_ENTITY~LOAD_AS.

  ENDMETHOD.

  METHOD ZIF_CRM_ENTITY~REFRESH.

  ENDMETHOD.

  METHOD ZIF_CRM_ENTITY~SET_ATTRIBUTE_VALUE.

  ENDMETHOD.

ENDCLASS.
